use role ACCOUNTADMIN;
use warehouse COMPUTE_WH;

----------------------
----- DEV start ------
----------------------

CREATE ROLE IF NOT EXISTS ROLE_TRANSFORM_DEV COMMENT='dev transform role';

CREATE WAREHOUSE IF NOT EXISTS WH_TRANSFORM_DEV
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 120
  AUTO_RESUME = true
  INITIALLY_SUSPENDED = TRUE;

GRANT ALL ON WAREHOUSE WH_TRANSFORM_DEV TO ROLE ROLE_TRANSFORM_DEV;


CREATE USER IF NOT EXISTS LD_USER
    PASSWORD='TO-BE-GENERATED'
	DEFAULT_ROLE=ROLE_TRANSFORM_DEV
	DEFAULT_WAREHOUSE=WH_TRANSFORM_DEV
    MUST_CHANGE_PASSWORD=TRUE
	COMMENT='dbt dev User';

GRANT ROLE ROLE_TRANSFORM_DEV TO USER LD_USER;


CREATE DATABASE IF NOT EXISTS LD_RAW;
CREATE DATABASE IF NOT EXISTS LD_ANALYTICS_DEV;


GRANT USAGE ON DATABASE LD_RAW TO ROLE ROLE_TRANSFORM_DEV;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE LD_RAW TO ROLE ROLE_TRANSFORM_DEV;
GRANT USAGE ON ALL SCHEMAS IN DATABASE LD_RAW TO ROLE ROLE_TRANSFORM_DEV;
GRANT SELECT ON FUTURE TABLES IN DATABASE LD_RAW TO ROLE ROLE_TRANSFORM_DEV;
GRANT SELECT ON ALL TABLES IN DATABASE LD_RAW TO ROLE ROLE_TRANSFORM_DEV;
GRANT SELECT ON FUTURE VIEWS IN DATABASE LD_RAW TO ROLE ROLE_TRANSFORM_DEV;
GRANT SELECT ON ALL VIEWS IN DATABASE LD_RAW TO ROLE ROLE_TRANSFORM_DEV;


GRANT ALL ON DATABASE LD_ANALYTICS_DEV TO ROLE ROLE_TRANSFORM_DEV;
----------------------
------ DEV end -------
----------------------



----------------------
-- Production start --
----------------------

CREATE ROLE IF NOT EXISTS ROLE_TRANSFORM_PROD COMMENT='prod transform role';

CREATE WAREHOUSE IF NOT EXISTS WH_TRANSFORM_PROD
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 120
  AUTO_RESUME = true
  INITIALLY_SUSPENDED = TRUE;

GRANT ALL ON WAREHOUSE WH_TRANSFORM_PROD TO ROLE ROLE_TRANSFORM_PROD;


CREATE USER IF NOT EXISTS PROD_SERVICE_USER
    PASSWORD='TO-BE-GENERATED'
	DEFAULT_ROLE=ROLE_TRANSFORM_PROD
	DEFAULT_WAREHOUSE=WH_TRANSFORM_PROD
    MUST_CHANGE_PASSWORD=TRUE
	COMMENT='dbt service user for Production';

GRANT ROLE ROLE_TRANSFORM_PROD TO USER PROD_SERVICE_USER;


CREATE DATABASE IF NOT EXISTS LD_ANALYTICS_PROD;


GRANT USAGE ON DATABASE LD_RAW TO ROLE ROLE_TRANSFORM_PROD;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE LD_RAW TO ROLE ROLE_TRANSFORM_PROD;
GRANT USAGE ON ALL SCHEMAS IN DATABASE LD_RAW TO ROLE ROLE_TRANSFORM_PROD;
GRANT SELECT ON FUTURE TABLES IN DATABASE LD_RAW TO ROLE ROLE_TRANSFORM_PROD;
GRANT SELECT ON ALL TABLES IN DATABASE LD_RAW TO ROLE ROLE_TRANSFORM_PROD;
GRANT SELECT ON FUTURE VIEWS IN DATABASE LD_RAW TO ROLE ROLE_TRANSFORM_PROD;
GRANT SELECT ON ALL VIEWS IN DATABASE LD_RAW TO ROLE ROLE_TRANSFORM_PROD;


GRANT ALL ON DATABASE LD_ANALYTICS_PROD TO ROLE ROLE_TRANSFORM_PROD;

----------------------
--- Production end ---
----------------------